### ISSUE TITLE
Create and Configure GitHub  Repository

### ISSUE THREAD

**Issue by Sydney1v1** [Sydney1v1/CMPG-323-Overview-2022-34321225#1]
## Milestones
- [ ] Create a repository named ‘CMPG 323 Overview - <add your student number>’
- [ ]  Project 1 Submission: Deadline – 12 August
- [ ] Project 2 Submission: Deadline – 5 September
- [ ] Project 3 Submission: Deadline – 26 September
- [ ] Project 4 Submission: Deadline – 17 October
- [ ] Project 5 Submission: Deadline – 31 October
- [ ] Exam (POE) Submission: No deadline
